apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 5m
  chart:
    spec:
      chart: traefik
      version: "35.2.0"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      interval: 1m
  values:
    additionalArguments:
      - --providers.kubernetesIngress.ingressEndpoint.publishedService=traefik/traefik
      - --entrypoints.websecure.forwardedHeaders.insecure
      - --entrypoints.web.forwardedHeaders.insecure
      - --entryPoints.web.forwardedHeaders.trustedIPs=0.0.0.0/0
      - --entryPoints.web.proxyProtocol.trustedIPs=0.0.0.0/0
      - --entryPoints.websecure.forwardedHeaders.trustedIPs=0.0.0.0/0
      - --entryPoints.websecure.proxyProtocol.trustedIPs=0.0.0.0/0       
    service:
      annotations:    
        loadbalancer.openstack.org/keep-floatingip: "true"
      spec: 
        externalTrafficPolicy: Local      
    deployment:
      kind: DaemonSet
    providers:  
      kubernetesCRD:
         nativeLBByDefault: true
      kubernetesIngress:
        nativeLBByDefault: true  
      kubernetesGateway:
        enabled: true
        nativeLBByDefault: true
    ingressRoute:
      dashboard:
        enabled: false
    gateway:
      annotations:
        dns.gardener.cloud/dnsnames: "*"
        dns.gardener.cloud/class: garden
        cert.gardener.cloud/purpose: managed
      enabled: true
      namespacePolicy: All
      listeners:
        web:
          port: 8000
          hostname: ""
          protocol: HTTP
          namespacePolicy: All
        https-jellyfin:
          port: 8443
          hostname: "jellyfin.cluster.domain"
          protocol: HTTPS
          namespacePolicy: All
          mode: Terminate
          certificateRefs:
          - name: jellyfin-tls
            namespace: traefik
    web:
      redirectTo: websecure
    persistence:
      enabled: false
    podSecurityContext: null
    tls:
      options:
        default:
          cipherSuites:
            - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
            - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
            - TLS_AES_256_GCM_SHA384
            - TLS_CHACHA20_POLY1305_SHA256
          curvePreferences:
            - CurveP521
            - CurveP384
          minVersion: VersionTLS12
          sniStrict: true
    logs:
      general:
        level: "INFO"
      access:
        enabled: true